### ISSUE TITLE
Knative Operator v1.1.2 bug means it expects `namespace` `istio-system` to exist

### ISSUE THREAD

**Issue by ca-scribner** [canonical/knative-operators#12]
[this bug](https://github.com/knative/operator/issues/565) in knative operator means that it will fail to deploy serving instances if `istio-system` namespace does not exist.  If you create this namespace, it appears to work properly (apart from creating some unnecessary objects in that namespace)

**Comment by DnPlas** [comment]
This issue should be fixed after we migrate to KNative >= 1.2.
