### ISSUE TITLE
`test_prometheus_grafana_integration` obs integration test fails

### ISSUE THREAD

**Issue by DnPlas** [canonical/knative-operators#127]
`prometheus-k8s` and `prometheus-scrape-config-k8s` seem to not get up and ready when running observability integration tests, which causes the `wait_for_idle` to timeout and the test case to fail with message:

```
  File "/home/runner/work/knative-operators/knative-operators/.tox/cos-integration/lib/python3.8/site-packages/juju/model.py", line 2616, in wait_for_idle
    raise jasyncio.TimeoutError("Timed out waiting for model:\n" + busy)
asyncio.exceptions.TimeoutError: Timed out waiting for model:
prometheus-k8s/0 [idle] maintenance: 
```

For logs and details see the [latest obs integration tests job](https://github.com/canonical/knative-operators/actions/runs/5643440038/job/15286770503#step:4:551) for #125

**Comment by ca-scribner** [comment]
These tests work fine for me locally.  I have a suspicion that prometheus might not be starting due to not enough CPU on the runner, but no data yet to support this.

**Comment by ca-scribner** [comment]
when I execute this locally, I see from `kubectl describe node` 2160m of CPU requests, with the prometheus workload being 200m.  iirc, github runners have 2CPU, so by chance it might be that prometheus in this test just exceeds the 2CPU limit of the runner.

**Comment by ca-scribner** [comment]
We tested this CI again after removing metallb (which requests 200m cpu) and the CI [ran successfully](https://github.com/canonical/knative-operators/actions/runs/5671453019).  So either metallb is somehow blocking the tests, or it is a CPU requests limit

**Comment by ca-scribner** [comment]
To debug this completely, we could add a `kubectl describe nodes` output at the end to see the state of CPU requests
