### ISSUE TITLE
Add config option to knative-eventing to set the version

### ISSUE THREAD

**Issue by NohaIhab** [canonical/knative-operators#136]
`knative-eventing` is missing a config option to specify the component version, similar to the one in [`knative-serving`](https://github.com/canonical/knative-operators/blob/main/charms/knative-serving/config.yaml#L5-L8).

**Comment by orfeas-k** [comment]
Note that when we resolve this bug, we should update also the [get-images script](https://github.com/canonical/knative-operators/pull/141) to use the version config when gathering images.
