### ISSUE TITLE
KSVC failed to start behind proxy with `RevisionFailed` reason: `failed to resolve image to digest`

### ISSUE THREAD

**Issue by NohaIhab** [canonical/knative-operators#204]
### Bug Description

During working on https://github.com/canonical/charmed-kubeflow-uats/issues/75, the kserve UAT fails behind proxy due to Knative Service failing to start.
The Knative Service is not `Ready` with the `RevisionFailed` reason.
The logs show that the Knative Serving controller is failing to resolve the image tag to digest for `charmedkubeflow/sklearnserver:0.11.2-e54c69e` image.

### To Reproduce

1. Deploy `kubeflow` bundle `1.9/beta` behind proxy
2. Run the [KServe UAT](https://github.com/canonical/charmed-kubeflow-uats/blob/main/tests/notebooks/kserve/kserve-integration.ipynb)
3. Describe the ksvc

### Environment

microk8s 1.29-strict/stable
juju 3.4.4
CKF 1.9/beta

### Relevant Log Output

```shell
Revision "sklearn-iris-predictor-00001" failed with message: Unable to fetch image "charmedkubeflow/sklearnserver:0.11.2-e54c69e": failed to resolve image to digest: Get "https://index.docker.io/v2/": context deadline exceeded.
```

**Comment by NohaIhab** [comment]
The knative service is failing to start because it is unable to resolve the image digest, we expect this to be due to not being able to reach the internet to get the digest.
What we can do here:
1. Configure the proxy envs in the serving controller - there are some pointers on doing this in the knative docs [here](https://knative.dev/v1.12-docs/serving/tag-resolution/#corporate-proxy) and [here](https://knative.dev/docs/install/operator/configuring-serving-cr/#override-the-environment-variables)
2. Skip tag resolution for the server registries to avoid bumping into the issue

**Comment by NohaIhab** [comment]
## Experimenting with option (1)
to configure the proxy envs in the serving controller:
1. edited the `knative-serving` CR manifest as follows:
```
--- a/charms/knative-serving/src/manifests/KnativeServing.yaml.j2
+++ b/charms/knative-serving/src/manifests/KnativeServing.yaml.j2
@@ -6,6 +6,17 @@ metadata:
   namespace: {{ serving_namespace }}
 spec:
   version: {{ serving_version }}
+  workloads:
+  - name: controller
+    env:
+    - container: controller
+      envVars:
+      - name: HTTP_PROXY
+        value: http://10.0.13.50:3128
+      - name: HTTPS_PROXY
+        value: http://10.0.13.50:3128
+      - name: NO_PROXY
+        value: 10.152.183.0/24
   config:
     deployment:
       progress-deadline: {{ progress_deadline}}
```
where:
* `HTTP_PROXY` and `HTTPS_PROXY` have the values of the proxy server
* `NO_PROXY` has the value of the service cluster ip range:
```
cat /var/snap/microk8s/current/args/kube-apiserver | grep service-cluster-ip-range
--service-cluster-ip-range=10.152.183.0/24
```
2. re-packed the `knative-serving` charm
3. refreshed the `knative-serving` charm from `latest/beta` to the local one
4. Ran the kserve UATs with the modification of adding the proxy envs to the `V1ObjectMeta` of ISVC definition

## Results
* I no longer see the image tag resolution error
* the KSVC is in `Unknown` state with Reason `RevisionMissing`
* describing the KSVC I see:
```
Name:         sklearn-iris-predictor
Namespace:    admin
Labels:       component=predictor
              notebook-proxy=true
              serving.kserve.io/inferenceservice=sklearn-iris
Annotations:  serving.knative.dev/creator: system:serviceaccount:kubeflow:kserve-controller
              serving.knative.dev/lastModifier: system:serviceaccount:kubeflow:kserve-controller
API Version:  serving.knative.dev/v1
Kind:         Service
Metadata:
  Creation Timestamp:  2024-07-24T10:42:30Z
  Generation:          1
  Owner References:
    API Version:           serving.kserve.io/v1beta1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  InferenceService
    Name:                  sklearn-iris
    UID:                   3a249bb2-f2f5-492d-a48f-7ac5943822dc
  Resource Version:        87248
  UID:                     aa001a12-98e7-4c22-ba3d-922c23b91215
Spec:
  Template:
    Metadata:
      Annotations:
        autoscaling.knative.dev/class:                             kpa.autoscaling.knative.dev
        autoscaling.knative.dev/min-scale:                         1
        internal.serving.kserve.io/storage-initializer-sourceuri:  gs://kfserving-examples/models/sklearn/1.0/model
        prometheus.kserve.io/path:                                 /metrics
        prometheus.kserve.io/port:                                 8080
        sidecar.istio.io/inject:                                   false
      Creation Timestamp:                                          <nil>
      Labels:
        Component:                           predictor
        Notebook - Proxy:                    true
        serving.kserve.io/inferenceservice:  sklearn-iris
    Spec:
      Container Concurrency:  0
      Containers:
        Args:
          --model_name=sklearn-iris
          --model_dir=/mnt/models
          --http_port=8080
        Image:  charmedkubeflow/sklearnserver:0.13.0-119414c
        Name:   kserve-container
        Readiness Probe:
          Success Threshold:  1
          Tcp Socket:
            Port:  0
        Resources:
          Limits:
            Cpu:     1
            Memory:  2Gi
          Requests:
            Cpu:             1
            Memory:          2Gi
      Enable Service Links:  false
      Timeout Seconds:       300
  Traffic:
    Latest Revision:  true
    Percent:          100
Status:
  Conditions:
    Last Transition Time:        2024-07-24T10:42:31Z
    Status:                      Unknown
    Type:                        ConfigurationsReady
    Last Transition Time:        2024-07-24T10:42:31Z
    Message:                     Configuration "sklearn-iris-predictor" is waiting for a Revision to become ready.
    Reason:                      RevisionMissing
    Status:                      Unknown
    Type:                        Ready
    Last Transition Time:        2024-07-24T10:42:31Z
    Message:                     Configuration "sklearn-iris-predictor" is waiting for a Revision to become ready.
    Reason:                      RevisionMissing
    Status:                      Unknown
    Type:                        RoutesReady
  Latest Created Revision Name:  sklearn-iris-predictor-00001
  Observed Generation:           1
  URL:                           http://sklearn-iris-predictor.admin.10.64.140.43.nip.io
Events:
  Type    Reason   Age   From                Message
  ----    ------   ----  ----                -------
  Normal  Created  5m3s  service-controller  Created Configuration "sklearn-iris-predictor"
  Normal  Created  5m3s  service-controller  Created Route "sklearn-iris-predictor"
```

**Comment by NohaIhab** [comment]
## Conclusion
This issue expanded to be 2 issues in fact that are currently blocking serving in CKF from working correctly behind proxy:
1. knative tag-to-digest resolution failing
2. kserve model download failing
Both issues are due to the pods responsible for pulling these artifacts/data not being able to establish a connection to their targets, and thus they need to have the proxy env vars set in order to unblock.

## Proposed fix
1. Introduce a `proxy` and `no-proxy` config to `kserve-controller` and `knative-serving` charms
2. Modify the manifests template for each of:
* `KnativeServing.yaml.j2` in `knative-serving` charm
* `cluster_storage_containers.yaml.j2` in `kserve-controller` charm
to have the proxy env vars set optionally, if they are set in the charm config.

**Comment by kimwnasptd** [comment]
@NohaIhab excellent job getting to the bottom of it and documenting everything!

I also agree with adding config options for the proxy to the `kserve-controller` and `kserve-serving` charms, which will end up altering the applied manifests. It's actually quite nice to see the charms to abstract this and only have a lean configuration for the proxy to the user!

My only concern is if we should have just one `proxy` config option, or make it 1-1 with the env var and introduce the following config options: `http-proxy`, `https-proxy`, `no-proxy`

**Comment by NohaIhab** [comment]
@kimwnasptd good point, I think we can even make it more clear by specifying for which container this proxy env is being set. For exmaple in `knative-serving`, make the config name `controller-http-proxy`, `controller-https-proxy`, and `controller-no-proxy`.
In `kserve-controller`, it can be `storage-initializer-http-proxy` .. etc.

**Comment by kimwnasptd** [comment]
IMO sticking to just expressing the functionality, and not also including the component, in the config name will provide a better UX.

The users don't necessarily care (AFAIK) for configuring different proxy settings for the different components of the same Knative Charm. They'd care about telling the charm what the proxy values are and then it's up to the Charm to do all the configurations wherever necessary.

The above is for a hypothetical scenario that in the future we might need `storage-initializer-http-proxy` and `queue-http-proxy` (random thought), for the `kserve-controller` charm. Users wouldn't care to put different values for the different sub-components and would only want to pass them once to the `kserve-controller` charm and then the charm configuring everything.

**Comment by orfeas-k** [comment]
Closed by above linked PRs
