### ISSUE TITLE
Integrate `net-istio-webhook` rock

### ISSUE THREAD

**Issue by mvlassis** [canonical/knative-operators#241]
### Context

Change the image used in the corresponding charm to new rock image from our team's registry

### What needs to get done

- Change the image used in the corresponding charm to new rock image from our team's registry

### Definition of Done

The rock is integrated, and all the integration tests pass.

**Comment by misohu** [comment]
We decided for now to change the value in the config.yaml but in the future we want to use this https://github.com/canonical/knative-operators/issues/247
