### ISSUE TITLE
Explore the responsibilities of `net-istio/cmd/controller` image

### ISSUE THREAD

**Issue by NohaIhab** [canonical/knative-operators#250]
### Context

We need to better understand what knative images are responsible to conclude what integration tests are missing there.

### What needs to get done

Explore and document what `knative-releases/knative.dev/net-istio/cmd/controller`  image is doing / responsible for.

### Definition of Done

Responsibilities of `knative-releases/knative.dev/net-istio/cmd/controller` image are well understood and documented.

**Comment by DnPlas** [comment]
https://github.com/canonical/knative-operators/issues/249#issuecomment-2521764509 exposes all the information required to understand where this image is used.

**Comment by DnPlas** [comment]
Same as #294
