### ISSUE TITLE
Explore the responsibilities of `migrate` image

### ISSUE THREAD

**Issue by NohaIhab** [canonical/knative-operators#251]
### Context

We need to better understand what knative images are responsible to conclude what integration tests are missing there.

### What needs to get done

Explore and document what `knative-releases/knative.dev/pkg/apiextensions/storageversion/cmd/migrate` image is doing / responsible for.

### Definition of Done

Responsibilities of `knative-releases/knative.dev/pkg/apiextensions/storageversion/cmd/migrate` image are well understood and documented.

**Comment by DnPlas** [comment]
According to the [Knative Serving installation files](https://knative.dev/docs/install/yaml-install/serving/serving-installation-files/#knative-serving-installation-files), there is a `storage-version-migration-serving- Job` that:

> Migrates the storage version of Knative resources, including Service, Route, Revision, and Configuration, from v1alpha1 and v1beta1 to v1. Required by upgrade from version 0.18 to 0.19.

**Comment by misohu** [comment]
The source code for the ko image of migrator can be found here:
[Knative/pkg - migrate source code](https://github.com/knative/pkg/blob/release-1.12/apiextensions/storageversion/cmd/migrate/main.go)

The key file for understanding the migration process is [migrator.go](https://github.com/knative/pkg/blob/release-1.12/apiextensions/storageversion/migrator.go). Essentially, this component is responsible for upgrading all Knative resources to their latest storage versions.

Below are the arguments used when executing the migrator in the pod. Yaml from `kubectl get po -n knative-serving  storage-version-migration-serving-serving-1.12.4-<id> -o yaml`.
```
...
- args:
  - services.serving.knative.dev
  - configurations.serving.knative.dev
  - revisions.serving.knative.dev
  - routes.serving.knative.dev
  - domainmappings.serving.knative.dev
...
```
These represent the target resources that the migrator upgrades during its execution.

Migrator image runs as a Kubernetes Job once when the serving part is deployed.

**Comment by DnPlas** [comment]
This has been reviewed by @orfeas-k , nothing else to add, but feel free to re-open if needed.
